auto_ecole:
    resource: "@AutoEcoleBundle/Resources/config/routing.yml"
    prefix:   /auto

annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /annonce

actualite:
    resource: "@ActualiteBundle/Resources/config/routing.yml"
    prefix:   /act

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclam

voiture:
    resource: "@VoitureBundle/Resources/config/routing.yml"
    prefix:   /carManager

karhabty:
    resource: "@KarhabtyBundle/Resources/config/routing.yml"
    prefix:   /

template:
    resource: "@TemplateBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



